# Generated by Django 4.1.1 on 2023-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=112)),
                ('L_name', models.CharField(max_length=112)),
                ('email', models.CharField(max_length=112)),
                ('Phone', models.CharField(max_length=12)),
                ('Query', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
